apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'maven-publish'

android {
    compileSdkVersion 29

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 29
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFile 'proguard-rules.pro'
        }
    }

    lintOptions {
        warning 'InvalidPackage'
        ignore 'MissingTranslation', 'ExtraTranslation', 'MissingDefaultResource'
        abortOnError false
    }

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/DEPENDENCIES'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    testOptions {
        unitTests {
            includeAndroidResources = false
            returnDefaultValues = true
        }
    }
}

dependencies {
    implementation 'androidx.startup:startup-runtime:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"

    implementation 'com.github.Arrowyi.NetScope:NetScope:v3.2.8'
    implementation 'com.github.Arrowyi.NetScope:NetScopeHook:v3.2.8'

    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:3.2.4'

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId    = 'com.github.Arrowyi'
                artifactId = 'NetMonitor'
                version    = project.findProperty('VERSION_NAME') ?: '1.0.0'
            }
        }
    }
}
